#!/usr/bin/env python

import time

import unicornhat as unicorn

unicorn.set_layout(unicorn.AUTO)
unicorn.rotation(180)
unicorn.brightness(0.5)
width, height = unicorn.get_shape()


colors = {
    'red': {'r': 255, 'g': 0, 'b': 0},
    'green': {'r': 0, 'g': 255, 'b': 0},
    'blue': {'r': 0, 'g': 0, 'b': 255},
    'yellow': {'r': 255, 'g': 255, 'b': 0},
    'orange': {'r': 255, 'g': 128, 'b': 0},
    'purple': {'r': 255, 'g': 0, 'b': 255},
    'cyan': {'r': 0, 'g': 255, 'b': 255},
    'gray': {'r': 128, 'g': 128, 'b': 128},
}

patterns = [
    [
        {'x': 0, 'y': 7,  'color': 'blue'},
        {'x': 1, 'y': 5,  'color': 'blue'},
        {'x': 1, 'y': 6,  'color': 'blue'},
        {'x': 2, 'y': 5,  'color': 'blue'},
        {'x': 3, 'y': 5,  'color': 'blue'},
        {'x': 4, 'y': 5,  'color': 'blue'},
        {'x': 5, 'y': 5,  'color': 'blue'},
        {'x': 6, 'y': 5,  'color': 'blue'},
        {'x': 6, 'y': 6,  'color': 'blue'},
        {'x': 7, 'y': 7,  'color': 'blue'},
        {'x': 5, 'y': 4,  'color': 'blue'},
        {'x': 5, 'y': 3,  'color': 'blue'},
        {'x': 4, 'y': 2,  'color': 'blue'},
        {'x': 3, 'y': 2,  'color': 'blue'},
        {'x': 2, 'y': 3,  'color': 'blue'},
        {'x': 2, 'y': 4,  'color': 'blue'},
    ],
    [
        {'x': 0, 'y': 2, 'color': 'green'},
        {'x': 0, 'y': 3, 'color': 'green'},
        {'x': 0, 'y': 4, 'color': 'green'},
        {'x': 0, 'y': 5, 'color': 'green'},
        {'x': 0, 'y': 6, 'color': 'green'},
        {'x': 0, 'y': 7, 'color': 'green'},
        {'x': 1, 'y': 2, 'color': 'green'},
        {'x': 1, 'y': 5, 'color': 'green'},
        {'x': 1, 'y': 7, 'color': 'green'},
        {'x': 2, 'y': 2, 'color': 'green'},
        {'x': 2, 'y': 5, 'color': 'green'},
        {'x': 2, 'y': 7, 'color': 'green'},
        {'x': 3, 'y': 2, 'color': 'green'},
        {'x': 3, 'y': 5, 'color': 'green'},
        {'x': 3, 'y': 7, 'color': 'green'},
        {'x': 4, 'y': 2, 'color': 'green'},
        {'x': 4, 'y': 5, 'color': 'green'},
        {'x': 4, 'y': 7, 'color': 'green'},
    ],
    [
        {'x': 1, 'y': 1, 'color': 'yellow'},
        {'x': 1, 'y': 2, 'color': 'yellow'},
        {'x': 1, 'y': 3, 'color': 'yellow'},
        {'x': 1, 'y': 4, 'color': 'yellow'},
        {'x': 1, 'y': 5, 'color': 'yellow'},
        {'x': 1, 'y': 6, 'color': 'yellow'},
        {'x': 1, 'y': 7, 'color': 'yellow'},
        {'x': 2, 'y': 7, 'color': 'yellow'},
        {'x': 3, 'y': 7, 'color': 'yellow'},
        {'x': 4, 'y': 7, 'color': 'yellow'},
        {'x': 5, 'y': 7, 'color': 'yellow'},
    ],
    [
        {'x': 0, 'y': 2, 'color': 'blue'},
        {'x': 0, 'y': 3, 'color': 'blue'},
        {'x': 0, 'y': 4, 'color': 'blue'},
        {'x': 1, 'y': 1, 'color': 'blue'},
        {'x': 1, 'y': 5, 'color': 'blue'},
        {'x': 2, 'y': 2, 'color': 'blue'},
        {'x': 2, 'y': 6, 'color': 'blue'},
        {'x': 3, 'y': 2, 'color': 'blue'},
        {'x': 3, 'y': 6, 'color': 'blue'},
        {'x': 4, 'y': 2, 'color': 'blue'},
        {'x': 4, 'y': 6, 'color': 'blue'},
        {'x': 5, 'y': 1, 'color': 'blue'},
        {'x': 5, 'y': 6, 'color': 'blue'},
        {'x': 6, 'y': 1, 'color': 'blue'},
        {'x': 6, 'y': 6, 'color': 'blue'},
        {'x': 7, 'y': 1, 'color': 'blue'},
        {'x': 7, 'y': 2, 'color': 'blue'},
        {'x': 7, 'y': 3, 'color': 'blue'},
        {'x': 7, 'y': 4, 'color': 'blue'},
        {'x': 7, 'y': 5, 'color': 'blue'},
    ],
    [
        {'x': 0, 'y': 0, 'color': 'orange'},
        {'x': 0, 'y': 1, 'color': 'orange'},
        {'x': 0, 'y': 2, 'color': 'orange'},
        {'x': 0, 'y': 3, 'color': 'orange'},
        {'x': 0, 'y': 4, 'color': 'orange'},
        {'x': 0, 'y': 5, 'color': 'orange'},
        {'x': 0, 'y': 6, 'color': 'orange'},
        {'x': 0, 'y': 7, 'color': 'orange'},
        {'x': 1, 'y': 0, 'color': 'blue'},
        {'x': 1, 'y': 1, 'color': 'blue'},
        {'x': 1, 'y': 2, 'color': 'blue'},
        {'x': 1, 'y': 3, 'color': 'blue'},
        {'x': 1, 'y': 4, 'color': 'blue'},
        {'x': 1, 'y': 5, 'color': 'blue'},
        {'x': 1, 'y': 6, 'color': 'blue'},
        {'x': 1, 'y': 7, 'color': 'blue'},
        {'x': 2, 'y': 0, 'color': 'yellow'},
        {'x': 2, 'y': 1, 'color': 'yellow'},
        {'x': 2, 'y': 2, 'color': 'yellow'},
        {'x': 2, 'y': 3, 'color': 'yellow'},
        {'x': 2, 'y': 4, 'color': 'yellow'},
        {'x': 2, 'y': 5, 'color': 'yellow'},
        {'x': 2, 'y': 6, 'color': 'yellow'},
        {'x': 2, 'y': 7, 'color': 'yellow'},
        {'x': 3, 'y': 0, 'color': 'purple'},
        {'x': 3, 'y': 1, 'color': 'purple'},
        {'x': 3, 'y': 2, 'color': 'purple'},
        {'x': 3, 'y': 3, 'color': 'purple'},
        {'x': 3, 'y': 4, 'color': 'purple'},
        {'x': 3, 'y': 5, 'color': 'purple'},
        {'x': 3, 'y': 6, 'color': 'purple'},
        {'x': 3, 'y': 7, 'color': 'purple'},
        {'x': 4, 'y': 0, 'color': 'red'},
        {'x': 4, 'y': 1, 'color': 'red'},
        {'x': 4, 'y': 2, 'color': 'red'},
        {'x': 4, 'y': 3, 'color': 'red'},
        {'x': 4, 'y': 4, 'color': 'red'},
        {'x': 4, 'y': 5, 'color': 'red'},
        {'x': 4, 'y': 6, 'color': 'red'},
        {'x': 4, 'y': 7, 'color': 'red'},
        {'x': 5, 'y': 0, 'color': 'cyan'},
        {'x': 5, 'y': 1, 'color': 'cyan'},
        {'x': 5, 'y': 2, 'color': 'cyan'},
        {'x': 5, 'y': 3, 'color': 'cyan'},
        {'x': 5, 'y': 4, 'color': 'cyan'},
        {'x': 5, 'y': 5, 'color': 'cyan'},
        {'x': 5, 'y': 6, 'color': 'cyan'},
        {'x': 5, 'y': 7, 'color': 'cyan'},
        {'x': 6, 'y': 0, 'color': 'gray'},
        {'x': 6, 'y': 1, 'color': 'gray'},
        {'x': 6, 'y': 2, 'color': 'gray'},
        {'x': 6, 'y': 3, 'color': 'gray'},
        {'x': 6, 'y': 4, 'color': 'gray'},
        {'x': 6, 'y': 5, 'color': 'gray'},
        {'x': 6, 'y': 6, 'color': 'gray'},
        {'x': 6, 'y': 7, 'color': 'gray'},
        {'x': 7, 'y': 0, 'color': 'green'},
        {'x': 7, 'y': 1, 'color': 'green'},
        {'x': 7, 'y': 2, 'color': 'green'},
        {'x': 7, 'y': 3, 'color': 'green'},
        {'x': 7, 'y': 4, 'color': 'green'},
        {'x': 7, 'y': 5, 'color': 'green'},
        {'x': 7, 'y': 6, 'color': 'green'},
        {'x': 7, 'y': 7, 'color': 'green'},
    ]
]

for pixels in patterns:
    unicorn.clear()
    for pixel in pixels:
        unicorn.set_pixel(
            pixel['x'],
            pixel['y'],
            colors[pixel['color']]['r'],
            colors[pixel['color']]['g'],
            colors[pixel['color']]['b']
        )
    unicorn.show()
    time.sleep(2)
